name: Build and Deploy

on:
  push:
    branches:
      - main  # Wird bei jedem Push auf main ausgeführt

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install  # Falls du Yarn oder pnpm nutzt, passe es an

      - name: Build Project
        run: npm run build  # Stelle sicher, dass dein Projekt ein "build"-Script hat

      - name: Deploy to FTP via SFTP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SFTP_HOST }}
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}
          source: "build/*"  # Der gebaute Ordner (ggf. anpassen)
          target: "/pfad/zum/ftp-root"  # Passe den Zielpfad an
          strip_components: 1
